permalink:           /:title/

# Setup
title:               redfux's mdkb 
tagline:             'my Markdown Knowledge Base'
description:         'my personal knowledge base to share with the world'
url:                 ''
baseurl:             '/mdkb'
paginate:            5

# About/contact
author:
  name:              Hannes
  url:               https://redfux.github.io/mdkb/
  email:             someone@example.com

# Includes an icon in the footer for each username you enter
footer-links:
  github: https://github.com/redfux

# Custom vars
version:             0.0.1
