permalink:           /:title/

# Setup
title:               redfux's mdkb 
tagline:             'my Markdown Knowledge Base'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 ''
baseurl:             '/mdkb'
paginate:            5

# About/contact
author:
  name:              Hannes
  url:               https://redfux.github.io/mdkb/
  email:             someone@example.com

# Includes an icon in the footer for each username you enter
footer-links:
  github: https://github.com/redfux

# Custom vars
version:             1.0.0
