permalink:           /:title/

# Setup
title:               redfux's mdkb 
tagline:             'my Markdown Knowledge Base'
description:         'my personal knowledge base to share with the world'
url:                 'https://redfux.github.io/mdkb/'
baseurl:             'https://redfux.github.io/mdkb/'
paginate:            100

# About/contact
author:
  name:              Hannes
  url:               https://redfux.github.io/mdkb/
  email:             someone@example.com

# Includes an icon in the footer for each username you enter
footer-links:
  github: redfux/mdkb

# Custom vars
version:             0.0.2
